version: '3.1'

services:
  mssql: 
    image: cabal-db-mssql
    ports:
      - 1433:1433
    volumes:
      - ./db/data:/var/opt/mssql/data:rw
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

  global_db_agent: 
    image: cabal-server
    command: "/usr/bin/GlobalDBAgent -l -c"
    env_file:
      - .env
    depends_on:
      - mssql
    ports:
      - 38180:38180

  auth_db_agent: 
    image: cabal-server
    command: "/usr/bin/AuthDBAgent -l -c"
    env_file:
      - .env
    depends_on:
      - mssql
    ports:
      - 32080:32080

  cash_db_agent: 
    image: cabal-server
    command: "/usr/bin/CashDBAgent -l -c"
    env_file:
      - .env
    depends_on:
      - mssql
    ports:
      - 38190:38190

  event_db_agent: 
    image: cabal-server
    command: "/usr/bin/EventDBAgent -l -c"
    env_file:
      - .env
    depends_on:
      - mssql
    ports:
      - 37110:37110

  pc_bang_db_agent: 
    image: cabal-server
    command: "/usr/bin/PCBangDBAgent -l -c"
    env_file:
      - .env
    depends_on:
      - mssql
    ports:
      - 38140:38140

  db_agent_01: 
    image: cabal-server
    command: "/usr/bin/DBAgent_01 -l -c"
    env_file:
      - .env
    depends_on:
      - mssql
    ports:
      - 38181:38181

  rock_and_roll_its: 
    image: cabal-server
    restart: always
    command: "world_svr_start /usr/bin/RockAndRollITS 60"
    env_file:
      - .env
    depends_on:
      - auth_db_agent
      - mssql
    ports:
      - 32001:32001

  global_mgr_svr: 
    image: cabal-server
    command: "global_mgr_svr"
    env_file:
      - .env
    depends_on:
      - rock_and_roll_its
      - global_db_agent
      - mssql
    ports:
      - 38170:38170

  party_svr_01: 
    image: cabal-server
    command: "/usr/bin/PartySvr_01 -l -c"
    env_file:
      - .env
    ports:
      - 38201:38201

  chat_node_01: 
    image: cabal-server
    command: "/usr/bin/ChatNode_01 -l -c"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - db_agent_01
      - mssql
    ports:
      - 38121:38121

  event_mgr_svr: 
    image: cabal-server
    command: "/usr/bin/EventMgrSvr -l -c"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - event_db_agent
      - mssql
    ports:
      - 38171:38171

  login_svr_01: 
    image: cabal-server
    command: "/usr/bin/LoginSvr_01 -l -c"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - global_db_agent
      - mssql
    ports:
      - 38101:38101

  agent_shop_01: 
    image: cabal-server
    command: "/usr/bin/AgentShop_01 -l -c"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - db_agent_01
      - chat_node_01
      - mssql
    ports:
      - 38151:38151

  world_svr_01_01: 
    image: cabal-server
    command: "/usr/bin/WorldSvr_01_01 -l -c"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - party_svr_01
      - db_agent_01
      - cash_db_agent
      - pc_bang_db_agent
      - chat_node_01
      - agent_shop_01
      - event_mgr_svr
      - mssql
    ports:
      - 38111:38111

  world_svr_01_02: 
    image: cabal-server
    command: "/usr/bin/WorldSvr_01_02 -l -c"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - party_svr_01
      - db_agent_01
      - cash_db_agent
      - pc_bang_db_agent
      - chat_node_01
      - agent_shop_01
      - event_mgr_svr
      - mssql
    ports:
      - 38112:38112

  world_svr_01_03: 
    image: cabal-server
    restart: always
    command: "world_svr_start /usr/bin/WorldSvr_01_03 240"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - party_svr_01
      - db_agent_01
      - cash_db_agent
      - pc_bang_db_agent
      - chat_node_01
      - agent_shop_01
      - event_mgr_svr
      - mssql
    ports:
      - 38113:38113

  world_svr_01_04: 
    image: cabal-server
    restart: always
    command: "world_svr_start /usr/bin/WorldSvr_01_04 240"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - party_svr_01
      - db_agent_01
      - cash_db_agent
      - pc_bang_db_agent
      - chat_node_01
      - agent_shop_01
      - event_mgr_svr
      - mssql
    ports:
      - 38114:38114

  world_svr_01_05: 
    image: cabal-server
    restart: always
    command: "world_svr_start /usr/bin/WorldSvr_01_05 240"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - party_svr_01
      - db_agent_01
      - cash_db_agent
      - pc_bang_db_agent
      - chat_node_01
      - agent_shop_01
      - event_mgr_svr
      - mssql
    ports:
      - 38115:38115

  world_svr_01_06: 
    image: cabal-server
    restart: always
    command: "world_svr_start /usr/bin/WorldSvr_01_06 240"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - party_svr_01
      - db_agent_01
      - cash_db_agent
      - pc_bang_db_agent
      - chat_node_01
      - agent_shop_01
      - event_mgr_svr
      - mssql
    ports:
      - 38116:38116

  world_svr_01_07: 
    image: cabal-server
    restart: always
    command: "world_svr_start /usr/bin/WorldSvr_01_07 240"
    env_file:
      - .env
    depends_on:
      - global_mgr_svr
      - party_svr_01
      - db_agent_01
      - cash_db_agent
      - pc_bang_db_agent
      - chat_node_01
      - agent_shop_01
      - event_mgr_svr
      - mssql
    ports:
      - 38117:38117